language: python
python:
  - "3.7.4"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install coverage codecov pytest-cov

env:
  global:
    - SECRET_KEY = $SECRET_KEY_DJANGO

script:
  - pytest --cov=fitness --cov=blog --cov=users

after_success:
  - codecov