language: python
python:
  - "3.7.4"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install coverage codecov pytest-cov

env:
  global:
    - SECRET_KEY = "m_4sgkzhiq2dqofwjm_%_uqbj0u3zsx#p)xkeha$o8fjr1=f$b"

script:
  - pytest
  - pytest --cov=.

after_success:
  - codecov