language: python
python:
  - "3.7.4"

services:
  - docker

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - pip install coverage codecov pytest-cov

env:
  global:
    - SECRET_KEY = 'ibd#eog7^)6-*!220!i(6q%$vhg*c95#7b^admqv4naxcznnuc'

script:
  - pytest --cov=fitness --cov=blog --cov=users

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t jchamblee1995/django_website:latest .

deploy:
  provider: script
  script: docker push jchamblee1995/django_website:latest
  on:
    branch: master

after_success:
  - codecov